# Generated by Django 4.0.1 on 2022-03-09 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last active'),
        ),
    ]
