# Generated by Django 4.0.1 on 2022-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_active_account_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_active',
            field=models.DateTimeField(default=None, null=True, verbose_name='last active'),
        ),
    ]
