# Generated by Django 4.0.1 on 2022-04-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_is_active_remove_account_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
    ]
