# Generated by Django 4.0.1 on 2022-03-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_last_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_active',
            new_name='last_seen',
        ),
        migrations.RemoveField(
            model_name='account',
            name='',
        ),
    ]
