# Generated by Django 4.0.1 on 2022-04-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(default=None, null=True, verbose_name='last seen'),
        ),
    ]
