# Generated by Django 4.0.1 on 2022-02-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=25, null=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.cube')),
            ],
        ),
    ]
