# Generated by Django 4.0.1 on 2022-03-02 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0004_alter_room_options_pass_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pass',
            new_name='Permit',
        ),
    ]
