# Generated by Django 4.0.1 on 2022-04-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0003_alter_room_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('scramble', models.TextField(blank=True, default=None, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(blank=True, default=None, null=True)),
                ('flag', models.TextField(blank=True, choices=[('DNF', 'DNF'), ('+2', '+2')], default=None, null=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.turn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('room', 'number'), name='unique_room_number'),
        ),
    ]
