name: Backend Heroku deploy
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Backend Heroku deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 #
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "multicubing-api"
          heroku_email: "ukasz.klimkiewicz@gmail.com"
          appdir: "back"
